// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: robotgo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveSmoothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32        `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32        `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []*anypb.Any `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MoveSmoothRequest) Reset() {
	*x = MoveSmoothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSmoothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSmoothRequest) ProtoMessage() {}

func (x *MoveSmoothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSmoothRequest.ProtoReflect.Descriptor instead.
func (*MoveSmoothRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{0}
}

func (x *MoveSmoothRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveSmoothRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveSmoothRequest) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type MoveSmoothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MoveSmoothResponse) Reset() {
	*x = MoveSmoothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSmoothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSmoothResponse) ProtoMessage() {}

func (x *MoveSmoothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSmoothResponse.ProtoReflect.Descriptor instead.
func (*MoveSmoothResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{1}
}

func (x *MoveSmoothResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MoveRelativeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32        `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32        `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []*anypb.Any `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MoveRelativeRequest) Reset() {
	*x = MoveRelativeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRelativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRelativeRequest) ProtoMessage() {}

func (x *MoveRelativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRelativeRequest.ProtoReflect.Descriptor instead.
func (*MoveRelativeRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{2}
}

func (x *MoveRelativeRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveRelativeRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveRelativeRequest) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type MoveRelativeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveRelativeResponse) Reset() {
	*x = MoveRelativeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRelativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRelativeResponse) ProtoMessage() {}

func (x *MoveRelativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRelativeResponse.ProtoReflect.Descriptor instead.
func (*MoveRelativeResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{3}
}

type MoveSmoothRelativeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32        `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32        `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []*anypb.Any `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MoveSmoothRelativeRequest) Reset() {
	*x = MoveSmoothRelativeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSmoothRelativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSmoothRelativeRequest) ProtoMessage() {}

func (x *MoveSmoothRelativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSmoothRelativeRequest.ProtoReflect.Descriptor instead.
func (*MoveSmoothRelativeRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{4}
}

func (x *MoveSmoothRelativeRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveSmoothRelativeRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveSmoothRelativeRequest) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type MoveSmoothRelativeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveSmoothRelativeResponse) Reset() {
	*x = MoveSmoothRelativeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSmoothRelativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSmoothRelativeResponse) ProtoMessage() {}

func (x *MoveSmoothRelativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSmoothRelativeResponse.ProtoReflect.Descriptor instead.
func (*MoveSmoothRelativeResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{5}
}

type GetMousePosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMousePosRequest) Reset() {
	*x = GetMousePosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMousePosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMousePosRequest) ProtoMessage() {}

func (x *GetMousePosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMousePosRequest.ProtoReflect.Descriptor instead.
func (*GetMousePosRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{6}
}

type GetMousePosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *GetMousePosResponse) Reset() {
	*x = GetMousePosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMousePosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMousePosResponse) ProtoMessage() {}

func (x *GetMousePosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMousePosResponse.ProtoReflect.Descriptor instead.
func (*GetMousePosResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{7}
}

func (x *GetMousePosResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GetMousePosResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ClickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*anypb.Any `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{8}
}

func (x *ClickRequest) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type ClickResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClickResponse) Reset() {
	*x = ClickResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResponse) ProtoMessage() {}

func (x *ClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResponse.ProtoReflect.Descriptor instead.
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{9}
}

type ScrollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []int32 `protobuf:"varint,3,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *ScrollRequest) Reset() {
	*x = ScrollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollRequest) ProtoMessage() {}

func (x *ScrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollRequest.ProtoReflect.Descriptor instead.
func (*ScrollRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{10}
}

func (x *ScrollRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ScrollRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type ScrollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScrollResponse) Reset() {
	*x = ScrollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollResponse) ProtoMessage() {}

func (x *ScrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollResponse.ProtoReflect.Descriptor instead.
func (*ScrollResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{11}
}

type ScrollMouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Direction []string `protobuf:"bytes,2,rep,name=direction,proto3" json:"direction,omitempty"`
}

func (x *ScrollMouseRequest) Reset() {
	*x = ScrollMouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollMouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollMouseRequest) ProtoMessage() {}

func (x *ScrollMouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollMouseRequest.ProtoReflect.Descriptor instead.
func (*ScrollMouseRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{12}
}

func (x *ScrollMouseRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollMouseRequest) GetDirection() []string {
	if x != nil {
		return x.Direction
	}
	return nil
}

type ScrollMouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScrollMouseResponse) Reset() {
	*x = ScrollMouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollMouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollMouseResponse) ProtoMessage() {}

func (x *ScrollMouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollMouseResponse.ProtoReflect.Descriptor instead.
func (*ScrollMouseResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{13}
}

type ScrollSmoothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To   int32   `protobuf:"varint,1,opt,name=to,proto3" json:"to,omitempty"`
	Args []int32 `protobuf:"varint,2,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *ScrollSmoothRequest) Reset() {
	*x = ScrollSmoothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollSmoothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollSmoothRequest) ProtoMessage() {}

func (x *ScrollSmoothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollSmoothRequest.ProtoReflect.Descriptor instead.
func (*ScrollSmoothRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{14}
}

func (x *ScrollSmoothRequest) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ScrollSmoothRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type ScrollSmoothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScrollSmoothResponse) Reset() {
	*x = ScrollSmoothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollSmoothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollSmoothResponse) ProtoMessage() {}

func (x *ScrollSmoothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollSmoothResponse.ProtoReflect.Descriptor instead.
func (*ScrollSmoothResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{15}
}

type ScrollRelativeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []int32 `protobuf:"varint,3,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *ScrollRelativeRequest) Reset() {
	*x = ScrollRelativeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollRelativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollRelativeRequest) ProtoMessage() {}

func (x *ScrollRelativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollRelativeRequest.ProtoReflect.Descriptor instead.
func (*ScrollRelativeRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{16}
}

func (x *ScrollRelativeRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollRelativeRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ScrollRelativeRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type ScrollRelativeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScrollRelativeResponse) Reset() {
	*x = ScrollRelativeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrollRelativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollRelativeResponse) ProtoMessage() {}

func (x *ScrollRelativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollRelativeResponse.ProtoReflect.Descriptor instead.
func (*ScrollRelativeResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{17}
}

type MilliSleepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tm int32 `protobuf:"varint,1,opt,name=tm,proto3" json:"tm,omitempty"`
}

func (x *MilliSleepRequest) Reset() {
	*x = MilliSleepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilliSleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilliSleepRequest) ProtoMessage() {}

func (x *MilliSleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilliSleepRequest.ProtoReflect.Descriptor instead.
func (*MilliSleepRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{18}
}

func (x *MilliSleepRequest) GetTm() int32 {
	if x != nil {
		return x.Tm
	}
	return 0
}

type MilliSleepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MilliSleepResponse) Reset() {
	*x = MilliSleepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MilliSleepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilliSleepResponse) ProtoMessage() {}

func (x *MilliSleepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilliSleepResponse.ProtoReflect.Descriptor instead.
func (*MilliSleepResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{19}
}

type SleepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tm int32 `protobuf:"varint,1,opt,name=tm,proto3" json:"tm,omitempty"`
}

func (x *SleepRequest) Reset() {
	*x = SleepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepRequest) ProtoMessage() {}

func (x *SleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepRequest.ProtoReflect.Descriptor instead.
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{20}
}

func (x *SleepRequest) GetTm() int32 {
	if x != nil {
		return x.Tm
	}
	return 0
}

type SleepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SleepResponse) Reset() {
	*x = SleepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepResponse) ProtoMessage() {}

func (x *SleepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepResponse.ProtoReflect.Descriptor instead.
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{21}
}

type CaptureScreenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []int32 `protobuf:"varint,1,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *CaptureScreenRequest) Reset() {
	*x = CaptureScreenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureScreenRequest) ProtoMessage() {}

func (x *CaptureScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureScreenRequest.ProtoReflect.Descriptor instead.
func (*CaptureScreenRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{22}
}

func (x *CaptureScreenRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type CaptureScreenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bitmap []byte `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
}

func (x *CaptureScreenResponse) Reset() {
	*x = CaptureScreenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureScreenResponse) ProtoMessage() {}

func (x *CaptureScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureScreenResponse.ProtoReflect.Descriptor instead.
func (*CaptureScreenResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{23}
}

func (x *CaptureScreenResponse) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

type CaptureGoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []int32 `protobuf:"varint,1,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *CaptureGoRequest) Reset() {
	*x = CaptureGoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureGoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureGoRequest) ProtoMessage() {}

func (x *CaptureGoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureGoRequest.ProtoReflect.Descriptor instead.
func (*CaptureGoRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{24}
}

func (x *CaptureGoRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type CaptureGoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bitmap []byte `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
}

func (x *CaptureGoResponse) Reset() {
	*x = CaptureGoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureGoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureGoResponse) ProtoMessage() {}

func (x *CaptureGoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureGoResponse.ProtoReflect.Descriptor instead.
func (*CaptureGoResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{25}
}

func (x *CaptureGoResponse) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

type CaptureImgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []int32 `protobuf:"varint,1,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *CaptureImgRequest) Reset() {
	*x = CaptureImgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureImgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureImgRequest) ProtoMessage() {}

func (x *CaptureImgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureImgRequest.ProtoReflect.Descriptor instead.
func (*CaptureImgRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{26}
}

func (x *CaptureImgRequest) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type CaptureImgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *CaptureImgResponse) Reset() {
	*x = CaptureImgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureImgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureImgResponse) ProtoMessage() {}

func (x *CaptureImgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureImgResponse.ProtoReflect.Descriptor instead.
func (*CaptureImgResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{27}
}

func (x *CaptureImgResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{28}
}

func (x *MoveRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{29}
}

type DragSmoothRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    int32        `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32        `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Args []*anypb.Any `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *DragSmoothRequest) Reset() {
	*x = DragSmoothRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragSmoothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragSmoothRequest) ProtoMessage() {}

func (x *DragSmoothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragSmoothRequest.ProtoReflect.Descriptor instead.
func (*DragSmoothRequest) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{30}
}

func (x *DragSmoothRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DragSmoothRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DragSmoothRequest) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type DragSmoothResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragSmoothResponse) Reset() {
	*x = DragSmoothResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robotgo_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragSmoothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragSmoothResponse) ProtoMessage() {}

func (x *DragSmoothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotgo_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragSmoothResponse.ProtoReflect.Descriptor instead.
func (*DragSmoothResponse) Descriptor() ([]byte, []int) {
	return file_robotgo_proto_rawDescGZIP(), []int{31}
}

var File_robotgo_proto protoreflect.FileDescriptor

var file_robotgo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x2e, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x5b, 0x0a, 0x13, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x16, 0x0a, 0x14,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x61, 0x0a, 0x19, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x28, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x6f, 0x76, 0x65, 0x53,
	0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x75, 0x73,
	0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x38,
	0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0d, 0x53, 0x63, 0x72,
	0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x63,
	0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x12,
	0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15,
	0x0a, 0x13, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x53,
	0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x22, 0x16, 0x0a, 0x14, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x53, 0x63, 0x72, 0x6f,
	0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6d,
	0x22, 0x14, 0x0a, 0x12, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x0c, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x74, 0x6d, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69,
	0x74, 0x6d, 0x61, 0x70, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x47,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2b, 0x0a, 0x11,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6d, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x29,
	0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x59, 0x0a, 0x11, 0x44, 0x72, 0x61,
	0x67, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x72, 0x61, 0x67, 0x53, 0x6d, 0x6f, 0x6f,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb9, 0x09, 0x0a, 0x07, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x47, 0x6f, 0x12, 0x49, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d,
	0x6f, 0x6f, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x6d, 0x6f,
	0x6f, 0x74, 0x68, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x75, 0x73,
	0x65, 0x50, 0x6f, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x05, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63,
	0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x0b, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x4d, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x4d,
	0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x4d, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c,
	0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x12, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x53, 0x6d,
	0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x53, 0x6d, 0x6f,
	0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a,
	0x0e, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x63, 0x72, 0x6f,
	0x6c, 0x6c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x53, 0x6c, 0x65,
	0x65, 0x70, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69,
	0x6c, 0x6c, 0x69, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x05, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x6c, 0x65, 0x65,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x46, 0x0a, 0x09, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x47, 0x6f, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x47,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x49, 0x6d, 0x67, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x44,
	0x72, 0x61, 0x67, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x53, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x41, 0x49, 0x2f, 0x43,
	0x6c, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x41, 0x49, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_robotgo_proto_rawDescOnce sync.Once
	file_robotgo_proto_rawDescData = file_robotgo_proto_rawDesc
)

func file_robotgo_proto_rawDescGZIP() []byte {
	file_robotgo_proto_rawDescOnce.Do(func() {
		file_robotgo_proto_rawDescData = protoimpl.X.CompressGZIP(file_robotgo_proto_rawDescData)
	})
	return file_robotgo_proto_rawDescData
}

var file_robotgo_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_robotgo_proto_goTypes = []interface{}{
	(*MoveSmoothRequest)(nil),          // 0: protobuf.MoveSmoothRequest
	(*MoveSmoothResponse)(nil),         // 1: protobuf.MoveSmoothResponse
	(*MoveRelativeRequest)(nil),        // 2: protobuf.MoveRelativeRequest
	(*MoveRelativeResponse)(nil),       // 3: protobuf.MoveRelativeResponse
	(*MoveSmoothRelativeRequest)(nil),  // 4: protobuf.MoveSmoothRelativeRequest
	(*MoveSmoothRelativeResponse)(nil), // 5: protobuf.MoveSmoothRelativeResponse
	(*GetMousePosRequest)(nil),         // 6: protobuf.GetMousePosRequest
	(*GetMousePosResponse)(nil),        // 7: protobuf.GetMousePosResponse
	(*ClickRequest)(nil),               // 8: protobuf.ClickRequest
	(*ClickResponse)(nil),              // 9: protobuf.ClickResponse
	(*ScrollRequest)(nil),              // 10: protobuf.ScrollRequest
	(*ScrollResponse)(nil),             // 11: protobuf.ScrollResponse
	(*ScrollMouseRequest)(nil),         // 12: protobuf.ScrollMouseRequest
	(*ScrollMouseResponse)(nil),        // 13: protobuf.ScrollMouseResponse
	(*ScrollSmoothRequest)(nil),        // 14: protobuf.ScrollSmoothRequest
	(*ScrollSmoothResponse)(nil),       // 15: protobuf.ScrollSmoothResponse
	(*ScrollRelativeRequest)(nil),      // 16: protobuf.ScrollRelativeRequest
	(*ScrollRelativeResponse)(nil),     // 17: protobuf.ScrollRelativeResponse
	(*MilliSleepRequest)(nil),          // 18: protobuf.MilliSleepRequest
	(*MilliSleepResponse)(nil),         // 19: protobuf.MilliSleepResponse
	(*SleepRequest)(nil),               // 20: protobuf.SleepRequest
	(*SleepResponse)(nil),              // 21: protobuf.SleepResponse
	(*CaptureScreenRequest)(nil),       // 22: protobuf.CaptureScreenRequest
	(*CaptureScreenResponse)(nil),      // 23: protobuf.CaptureScreenResponse
	(*CaptureGoRequest)(nil),           // 24: protobuf.CaptureGoRequest
	(*CaptureGoResponse)(nil),          // 25: protobuf.CaptureGoResponse
	(*CaptureImgRequest)(nil),          // 26: protobuf.CaptureImgRequest
	(*CaptureImgResponse)(nil),         // 27: protobuf.CaptureImgResponse
	(*MoveRequest)(nil),                // 28: protobuf.MoveRequest
	(*MoveResponse)(nil),               // 29: protobuf.MoveResponse
	(*DragSmoothRequest)(nil),          // 30: protobuf.DragSmoothRequest
	(*DragSmoothResponse)(nil),         // 31: protobuf.DragSmoothResponse
	(*anypb.Any)(nil),                  // 32: google.protobuf.Any
}
var file_robotgo_proto_depIdxs = []int32{
	32, // 0: protobuf.MoveSmoothRequest.args:type_name -> google.protobuf.Any
	32, // 1: protobuf.MoveRelativeRequest.args:type_name -> google.protobuf.Any
	32, // 2: protobuf.MoveSmoothRelativeRequest.args:type_name -> google.protobuf.Any
	32, // 3: protobuf.ClickRequest.args:type_name -> google.protobuf.Any
	32, // 4: protobuf.DragSmoothRequest.args:type_name -> google.protobuf.Any
	0,  // 5: protobuf.RobotGo.MoveSmooth:input_type -> protobuf.MoveSmoothRequest
	2,  // 6: protobuf.RobotGo.MoveRelative:input_type -> protobuf.MoveRelativeRequest
	4,  // 7: protobuf.RobotGo.MoveSmoothRelative:input_type -> protobuf.MoveSmoothRelativeRequest
	6,  // 8: protobuf.RobotGo.GetMousePos:input_type -> protobuf.GetMousePosRequest
	8,  // 9: protobuf.RobotGo.Click:input_type -> protobuf.ClickRequest
	10, // 10: protobuf.RobotGo.Scroll:input_type -> protobuf.ScrollRequest
	12, // 11: protobuf.RobotGo.ScrollMouse:input_type -> protobuf.ScrollMouseRequest
	14, // 12: protobuf.RobotGo.ScrollSmooth:input_type -> protobuf.ScrollSmoothRequest
	16, // 13: protobuf.RobotGo.ScrollRelative:input_type -> protobuf.ScrollRelativeRequest
	18, // 14: protobuf.RobotGo.MilliSleep:input_type -> protobuf.MilliSleepRequest
	20, // 15: protobuf.RobotGo.Sleep:input_type -> protobuf.SleepRequest
	22, // 16: protobuf.RobotGo.CaptureScreen:input_type -> protobuf.CaptureScreenRequest
	24, // 17: protobuf.RobotGo.CaptureGo:input_type -> protobuf.CaptureGoRequest
	26, // 18: protobuf.RobotGo.CaptureImg:input_type -> protobuf.CaptureImgRequest
	28, // 19: protobuf.RobotGo.Move:input_type -> protobuf.MoveRequest
	30, // 20: protobuf.RobotGo.DragSmooth:input_type -> protobuf.DragSmoothRequest
	1,  // 21: protobuf.RobotGo.MoveSmooth:output_type -> protobuf.MoveSmoothResponse
	3,  // 22: protobuf.RobotGo.MoveRelative:output_type -> protobuf.MoveRelativeResponse
	5,  // 23: protobuf.RobotGo.MoveSmoothRelative:output_type -> protobuf.MoveSmoothRelativeResponse
	7,  // 24: protobuf.RobotGo.GetMousePos:output_type -> protobuf.GetMousePosResponse
	9,  // 25: protobuf.RobotGo.Click:output_type -> protobuf.ClickResponse
	11, // 26: protobuf.RobotGo.Scroll:output_type -> protobuf.ScrollResponse
	13, // 27: protobuf.RobotGo.ScrollMouse:output_type -> protobuf.ScrollMouseResponse
	15, // 28: protobuf.RobotGo.ScrollSmooth:output_type -> protobuf.ScrollSmoothResponse
	17, // 29: protobuf.RobotGo.ScrollRelative:output_type -> protobuf.ScrollRelativeResponse
	19, // 30: protobuf.RobotGo.MilliSleep:output_type -> protobuf.MilliSleepResponse
	21, // 31: protobuf.RobotGo.Sleep:output_type -> protobuf.SleepResponse
	23, // 32: protobuf.RobotGo.CaptureScreen:output_type -> protobuf.CaptureScreenResponse
	25, // 33: protobuf.RobotGo.CaptureGo:output_type -> protobuf.CaptureGoResponse
	27, // 34: protobuf.RobotGo.CaptureImg:output_type -> protobuf.CaptureImgResponse
	29, // 35: protobuf.RobotGo.Move:output_type -> protobuf.MoveResponse
	31, // 36: protobuf.RobotGo.DragSmooth:output_type -> protobuf.DragSmoothResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_robotgo_proto_init() }
func file_robotgo_proto_init() {
	if File_robotgo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_robotgo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSmoothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSmoothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRelativeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRelativeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSmoothRelativeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSmoothRelativeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMousePosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMousePosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollMouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollMouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollSmoothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollSmoothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollRelativeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrollRelativeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilliSleepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MilliSleepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureScreenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureScreenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureGoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureGoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureImgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureImgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragSmoothRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robotgo_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragSmoothResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_robotgo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robotgo_proto_goTypes,
		DependencyIndexes: file_robotgo_proto_depIdxs,
		MessageInfos:      file_robotgo_proto_msgTypes,
	}.Build()
	File_robotgo_proto = out.File
	file_robotgo_proto_rawDesc = nil
	file_robotgo_proto_goTypes = nil
	file_robotgo_proto_depIdxs = nil
}
